version: "3.8"
services:
  postgres:
    container_name: "postgres"
    image: postgres:13.11-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
  hapi:
    container_name: "hapi"
    image: node:18.17.1
    ports:
      - "9090:9090"
    volumes:
      - type: bind
        source: ./hapi
        target: /app
    working_dir: /app
    command: bash -c "yarn && yarn start:dev"
    environment:
      HAPI_SERVER_PORT: "${HAPI_SERVER_PORT}"
      HAPI_SERVER_ADDRESS: "${HAPI_SERVER_ADDRESS}"
      HAPI_HASURA_URL: "${HAPI_HASURA_URL}"
      HAPI_HASURA_ADMIN_SECRET: "${HAPI_HASURA_ADMIN_SECRET}"
      HAPI_HOST_DOMAIN: "${HAPI_HOST_DOMAIN}"
      HAPI_POLYGON_NETWORK: "${HAPI_POLYGON_NETWORK}"
      HAPI_ISSUER_PUBLIC_KEY: "${HAPI_ISSUER_PUBLIC_KEY}"
      HAPI_CONTRACT_ADDRESS: "${HAPI_CONTRACT_ADDRESS}"
      HAPI_RPC_URL: "${HAPI_RPC_URL}"
      HAPI_ALCHEMY_KEY: "${HAPI_ALCHEMY_KEY}"
      HAPI_IPFS_NODE_URL: "${HAPI_IPFS_NODE_URL}"
      HAPI_PROOF_REQUEST: "${HAPI_PROOF_REQUEST}"
  hasura:
    container_name: "hasura"
    image: hasura/graphql-engine:v2.33.1.cli-migrations-v3
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ./hasura/migrations:/migrations
      - ./hasura/metadata:/metadata
      - ./hasura/seeds:/seeds
    environment:
      HASURA_GRAPHQL_DATABASE_URL: "${HASURA_GRAPHQL_DATABASE_URL}"
      HASURA_GRAPHQL_MIGRATIONS_DIR: /migrations
      HASURA_GRAPHQL_METADATA_DIR: /metadata
      HASURA_GRAPHQL_SEEDS_DIR: /seeds
      HASURA_GRAPHQL_ACTION_BASE_URL: "${HASURA_GRAPHQL_ACTION_BASE_URL}"
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      # Local Development Configurations It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "false"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ENABLE_LOGGING: "true"
      # disabled security for local development
      HASURA_GRAPHQL_ADMIN_SECRET: "${HASURA_GRAPHQL_ADMIN_SECRET}"
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: "${HASURA_GRAPHQL_UNAUTHORIZED_ROLE}"
  webapp:
    container_name: "webapp"
    image: node:16.14.0-alpine
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      - ./tmp/webapp/node_modules/:/app/node_modules/
      - type: bind
        source: ./webapp
        target: /app
    working_dir: /app
    command: bash -c "yarn && yarn start"
    environment:
      NEXT_PUBLIC_TAG: "${NEXT_PUBLIC_TAG}"
      NEXT_PUBLIC_TITLE: "${NEXT_PUBLIC_TITLE}"
      NEXT_PUBLIC_LOGO: "${NEXT_PUBLIC_LOGO}"
      NEXT_PUBLIC_FOOTER_LINKS: "${NEXT_PUBLIC_FOOTER_LINKS}"
      NEXT_PUBLIC_UAL_APP_NAME: "${NEXT_PUBLIC_UAL_APP_NAME}"
      NEXT_PUBLIC_UAL_API_PROTOCOL: "${NEXT_PUBLIC_UAL_API_PROTOCOL}"
      NEXT_PUBLIC_UAL_API_HOST: "${NEXT_PUBLIC_UAL_API_HOST}"
      NEXT_PUBLIC_UAL_API_PORT: "${NEXT_PUBLIC_UAL_API_PORT}"
      NEXT_PUBLIC_UAL_CHAIN_ID: "${NEXT_PUBLIC_UAL_CHAIN_ID}"
      NEXT_PUBLIC_HASURA_URL: "${NEXT_PUBLIC_HASURA_URL}"
volumes:
  postgres_data:
