apiVersion: v1
kind: ConfigMap
metadata:
  name: webapp-config
data:
  # webapp
  PORT: "${PORT}"
  NEXT_PUBLIC_TTILE: "${NEXT_PUBLIC_TTILE}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  # postgres
  POSTGRES_USER: "${POSTGRES_USER}"
  POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
  POSTGRES_DB: "${POSTGRES_DB}"
  POSTGRES_DATA: "${POSTGRES_DATA}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hapi-config
data:
  # hapi
  HAPI_SERVER_PORT: "${HAPI_SERVER_PORT}"
  HAPI_SERVER_ADDRESS: "${HAPI_SERVER_ADDRESS}"
  HAPI_HASURA_URL: "${HAPI_HASURA_URL}"
  HAPI_HASURA_ADMIN_SECRET: "${HAPI_HASURA_ADMIN_SECRET}"
  HAPI_HOST_DOMAIN: "${HAPI_HOST_DOMAIN}"
  HAPI_POLYGON_NETWORK: "${HAPI_POLYGON_NETWORK}"
  HAPI_ISSUER_PUBLIC_KEY: "${HAPI_ISSUER_PUBLIC_KEY}"
  HAPI_CONTRACT_ADDRESS: "${HAPI_CONTRACT_ADDRESS}"
  HAPI_RPC_URL: "${HAPI_RPC_URL}"
  HAPI_ALCHEMY_KEY: "${HAPI_ALCHEMY_KEY}"
  HAPI_IPFS_NODE_URL: "${HAPI_IPFS_NODE_URL}"
  HAPI_PROOF_REQUEST: "${HAPI_PROOF_REQUEST}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hasura-config
data:
  # hasura
  HASURA_GRAPHQL_ENABLE_CONSOLE: "${HASURA_GRAPHQL_ENABLE_CONSOLE}"
  HASURA_GRAPHQL_DATABASE_URL: "${HASURA_GRAPHQL_DATABASE_URL}"
  HASURA_GRAPHQL_ADMIN_SECRET: "${HASURA_GRAPHQL_ADMIN_SECRET}"
  HASURA_GRAPHQL_UNAUTHORIZED_ROLE: "${HASURA_GRAPHQL_UNAUTHORIZED_ROLE}"
  HASURA_GRAPHQL_ACTION_BASE_URL: "${HASURA_GRAPHQL_ACTION_BASE_URL}"
